#!/bin/bash
# EAS Build pre-install hook
# Writes EAS Secrets (available as env vars during build) into .env
# so react-native-dotenv can pick them up at bundle time.

set -euo pipefail

ENV_FILE=".env"

echo "# Auto-generated by EAS Build pre-install hook" > "$ENV_FILE"
echo "# Do not edit — values come from EAS Secrets" >> "$ENV_FILE"

if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
  echo "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}" >> "$ENV_FILE"
  echo "[eas-build] ANTHROPIC_API_KEY written to .env"
else
  echo "ANTHROPIC_API_KEY=" >> "$ENV_FILE"
  echo "[eas-build] WARNING: ANTHROPIC_API_KEY not set — app will use fallback breakdown"
fi
